package com.cobaltumapps.reddittoppostsappblank.retrofit.posts.data

import com.kolomoiets.reddittoppostsapp.retrofit.posts.data.subdata.Data
/* Autogenerated jsonToKotlinClass */
data class PostResponse(
    val `data`: Data,
    val kind: String
)